### ISSUE TITLE
Delete-function does not work properly

### ISSUE THREAD

**Issue by YanceyWang** [librehat/shadowsocks-qt5#64] opened 2015-03-11 02:40 UTC
Sometimes when i press `-`  button to delete a profile, the application window just disappears.
But sometimes it works fine.
I cant figure out why this happened。

**Comment by librehat** [comment] 2015-03-11 21:32
I can't reproduce this issue. Maybe record a video and convert it to gif and paste here?

**Comment by SmilingSun** [comment] 2015-03-15 02:50
I'm using Ubuntu, and the same thing happens. 
How to **record a video and convert it to gif and paste here?**

**Comment by librehat** [comment] 2015-03-15 11:46
@SmilingSun http://linux.die.net/man/1/byzanz-record

**Comment by librehat** [comment] 2015-04-06 11:38
Please supply more information, or this issue will be closed in next week.

**Closed** 2015-04-10 11:38 UTC
Labels: need more info
